WebApplication1/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class AboutController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/About/";

        public ActionResult RenderAbout()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_About.cshtml");
        }

    }
}

WebApplication1/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using WebApplication1.Models;
using Umbraco.Web;
using Umbraco.Core.Models;

namespace WebApplication1.Controllers
{
    public class BlogController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Blog/";

        public ActionResult RenderBlog()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Blog.cshtml");
        }

        public ActionResult RenderBlogPost()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_BlogPost.cshtml");
        }

        public ActionResult RenderBlogPostTitle()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_BlogPostTitleControls.cshtml");
        }

        public ActionResult RenderPostList()
        {
            List<BlogPreview> model = new List<BlogPreview>();
            IPublishedContent blogPage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf(1).Where(x => x.DocumentTypeAlias == "blog").FirstOrDefault();

            foreach (IPublishedContent page in blogPage.Children.OrderByDescending(x => x.UpdateDate))
            {
                int imageId = page.GetPropertyValue<int>("articleImage");
                var mediaItem = Umbraco.Media(imageId);

                model.Add(new BlogPreview(page.Name, page.GetPropertyValue<string>("articleIntro"), mediaItem.Url, page.Url));
            }
            return PartialView(PARTIAL_VIEW_FOLDER + "_PostList.cshtml", model);
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Home/";

        public ActionResult RenderIntro()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Intro.cshtml");
        }

        public ActionResult RenderHome()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Home.cshtml");
        }

    }
}

WebApplication1/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class NewsController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/News/";

        public ActionResult RenderNews()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_News.cshtml");
        }
  
    }
}

WebApplication1/Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;
using WebApplication1.Models;
using System.Runtime.Caching;
using Umbraco.Web;

namespace WebApplication1.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/SiteLayout/";

        public ActionResult RenderHeader()
        {
            List<NavigationListItem> nav = GetObjectFromCache<List<NavigationListItem>>("mainNav", 5, GetNavigationModelFromDatabase);
            return PartialView(PARTIAL_VIEW_FOLDER + "_Header.cshtml", nav);
        }

        public ActionResult RenderFooter()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Footer.cshtml");
        }

        public ActionResult RenderTitleControls()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_TitleControls.cshtml");
        }


        private List<NavigationListItem> GetNavigationModelFromDatabase()
        {
            IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            List<NavigationListItem> nav = new List<NavigationListItem>();
            nav.Add(new NavigationListItem(new NavigationLink(homePage.Url, homePage.Name)));
            nav.AddRange(GetChildNavigationList(homePage));
            return nav;
        }

        private List<NavigationListItem> GetChildNavigationList(IPublishedContent page)
        {
            List<NavigationListItem> listItems = null;
            var childPages = page.Children.Where("Visible").Where(x => x.Level <=2);
            if (childPages != null && childPages.Any() && childPages.Count() > 0)
            {
                listItems = new List<NavigationListItem>();
                foreach (var childPage in childPages)
                {
                    NavigationListItem listItem = new NavigationListItem(new NavigationLink(childPage.Url, childPage.Name));
                    listItem.Items = GetChildNavigationList(childPage);
                    listItems.Add(listItem);
                }
            }
            return listItems;

        }

        private static T GetObjectFromCache<T>(string cacheItemName, int cacheTimeInMinutes, Func<T> objectSettingFunction)
        {
            ObjectCache cache = MemoryCache.Default;
            var cachedObject = (T)cache[cacheItemName];
            if (cachedObject == null)
            {
                CacheItemPolicy policy = new CacheItemPolicy();
                policy.AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(cacheTimeInMinutes);
                cachedObject = objectSettingFunction();
                cache.Set(cacheItemName, cachedObject, policy);
            }
            return cachedObject;
        }
    }
}

WebApplication1/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@{ Html.RenderAction("RenderIntro", "Home");}
<article id="main">
    @{ Html.RenderAction("RenderAbout", "About");}
    <section class="wrapper style4 container">
        @CurrentPage.GetGridHtml("contentGrid", "bootstrap3")
    </section>
</article>

WebApplication1/Views/Blog.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

    @{ Html.RenderAction("RenderIntro", "Home");}
<article id="main">
    @{ Html.RenderAction("RenderBlog", "Blog");}
    @{ Html.RenderAction("RenderPostList", "Blog");}
</article>

WebApplication1/Views/BlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@{ Html.RenderAction("RenderBlogPost", "Blog");}
<article id="main">
    <section class="wrapper style4 container">
        @CurrentPage.GetGridHtml("contentGrid", "bootstrap3")
    </section>
</article>

WebApplication1/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@{ Html.RenderAction("RenderIntro", "Home");}
<article id="main">
    @{ Html.RenderAction("RenderHome", "Home");}
    <section class="wrapper style4 container">
        @CurrentPage.GetGridHtml("contentGrid", "bootstrap3")
    </section>
</article>

WebApplication1/Views/News.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@{ Html.RenderAction("RenderIntro", "Home");}

@{ Html.RenderAction("RenderNews", "News");}

WebApplication1/Views/WebBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}
<!DOCTYPE HTML>
<html>
<head>
    <title>Umbaro Page by Joona</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />


    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
    
    <link rel="stylesheet" href="~/Css/navigation.css" />
    <link rel="stylesheet" href="~/Css/news.css" />
    <link rel="stylesheet" href="~/Css/home.css" />
    <link rel="stylesheet" href="~/Css/global.css" />
    <link rel="stylesheet" href="~/Css/main.css" />
    <noscript><link rel="stylesheet" href="~/Css/noscript.css" /></noscript>
</head>
    <body class="index is-preload">
        <div id="page-wrapper">
            @{ Html.RenderAction("RenderHeader", "SiteLayout");}
            @RenderBody()

            @{ Html.RenderAction("RenderFooter", "SiteLayout");}

            <!-- Scripts -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery.dropotron.min.js"></script>
    <script src="~/Scripts/jquery.scrolly.min.js"></script>
    <script src="~/Scripts/jquery.scrollex.min.js"></script>
    <script src="~/Scripts/browser.min.js"></script>
    <script src="~/Scripts/breakpoints.min.js"></script>
    <script src="~/Scripts/util.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    </div>
    </body>
</html>