WebApplication1/Controllers/DatabaseController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data.SqlServerCe;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Services;
using umbraco.uicontrols;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class DatabaseController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/News/";    

        [HttpGet]
        public string GetTestimonials()

        {
            var list = new List<FeedbackModel>();

                list.Add(new FeedbackModel()
                {
                    postName = "Tämä postaus on C# listassa",
                    datePosted = DateTime.Now.ToString("MMMM dd"),
                    postContent = "Tämä postaus on haettu AJAX pyynnöllä. Tässä on paljon sisältöä. Sed tristique purus vitae volutpat commodo suscipit amet sed nibh." +
                    " Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper commodo suscipit amet sed nibh. " +
                    "Proin a ullamcorper sed blandit.",

                });

                list.Add(new FeedbackModel()
                {
                    postName = "Tämä postaus on kanssa samassa C# listassa",
                    datePosted = DateTime.Now.ToString("MMMM dd"),
                    postContent = "Tämä postaus on haettu myös AJAX pyynnöllä. Tässä on vielä enemmän sisältöä. Sed tristique purus vitae volutpat commodo suscipit amet sed nibh." +
                    " Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper commodo suscipit amet sed nibh. " +
                    "Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit amet sed nibh." +
                    " Proin a ullamcorper sed blandit. Sed tristique purus vitae volutpat commodo suscipit ullamcorper commodo suscipit amet sed nibh. " +
                    "Proin a ullamcorper sed blandit.",
                });

            JavaScriptSerializer serializer = new JavaScriptSerializer();
            return serializer.Serialize(list);
          

        }
        
        public ActionResult RenderDatabaseText()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_DatabaseText.cshtml");
        }

    }
}

WebApplication1/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class NewsController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/News/";

        public ActionResult RenderNews()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_News.cshtml");
        }
  
    }
}

WebApplication1/Views/Partials/News/_DatabaseText.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(getList);

    function getList() {
        
        ajaxReq = $.ajax({
            url: '/umbraco/Surface/Database/GetTestimonials',
            type: "GET",
            dataType: 'text',
            async: true,                
            success: function (result) {
                var JsonResult = JSON.parse(result)  
                
                    document.getElementById("WhoMadePost").innerHTML = JsonResult[0].postName + '<br>';
                    document.getElementById("DateAdded").innerHTML = JsonResult[0].datePosted + '<br>';
                    document.getElementById("PostContent").innerHTML = JsonResult[0].postContent;

                document.getElementById("WhoMadePost1").innerHTML = JsonResult[1].postName + '<br>';
                document.getElementById("DateAdded1").innerHTML = JsonResult[1].datePosted + '<br>';
                document.getElementById("PostContent1").innerHTML = JsonResult[1].postContent;
            },
            error: function () {
                console.log("Error");
            }
        });
       
    }

</script>

WebApplication1/Views/Partials/News/_News.cshtml
@inherits  UmbracoViewPage

<article id="main">

    <header class="special container">
        <span class="icon fa-paperclip"></span>
        <h2>@Html.Raw(Umbraco.AssignedContentItem.GetPropertyValue("pageIntro"))</h2>
        <p>
            @{ Html.RenderAction("RenderDatabaseText", "Database");}
        </p>
    </header>
    <section class="wrapper style4 container">
        <h2 id="WhoMadePost"></h2>
        <h3 id="DateAdded"></h3>
        <p id="PostContent"></p>
    </section>
    <section class="wrapper style4 container">
        <h2 id="WhoMadePost1"></h2>
        <h3 id="DateAdded1"></h3>
        <p id="PostContent1"></p>
    </section>


</article>